// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4nhBTkHfBditQ0hzd4tskvhowZ4Gefzg',
    appId: '1:434849707243:android:962203f490315a7b8b7aae',
    messagingSenderId: '434849707243',
    projectId: 'cheapify-b566f',
    storageBucket: 'cheapify-b566f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ZHWu1SQQb5WO5jsViTt2EmMC3lgUGng',
    appId: '1:434849707243:ios:f102799db42ed0bb8b7aae',
    messagingSenderId: '434849707243',
    projectId: 'cheapify-b566f',
    storageBucket: 'cheapify-b566f.appspot.com',
    iosClientId: '434849707243-b46fmfplhof7m62vbiuhgae6cac06l1e.apps.googleusercontent.com',
    iosBundleId: 'io.cheapify.cheapify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ZHWu1SQQb5WO5jsViTt2EmMC3lgUGng',
    appId: '1:434849707243:ios:f102799db42ed0bb8b7aae',
    messagingSenderId: '434849707243',
    projectId: 'cheapify-b566f',
    storageBucket: 'cheapify-b566f.appspot.com',
    iosClientId: '434849707243-b46fmfplhof7m62vbiuhgae6cac06l1e.apps.googleusercontent.com',
    iosBundleId: 'io.cheapify.cheapify',
  );
}
